name: senzu_player
description: >-
  Feature-rich Flutter video player with native state management, Native player.
version: 1.2.1
homepage: https://github.com/kenji-07/senzu_player
documentation: https://github.com/kenji-07/senzu_player/blob/main/README.md
repository: https://github.com/kenji-07/senzu_player

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.27.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.senzu.senzu_player
        pluginClass: SenzuPlayerPlugin
      ios:
        pluginClass: SenzuPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  # State management
  get: ^4.7.3
  # AES subtitle decryption
  pointycastle: ^4.0.0
  # HTTP
  http: ^1.6.0
  # IMA ads
  interactive_media_ads: ^0.3.0+16

  cached_network_image: ^3.4.1

  # Download
  sqflite: ^2.4.3
  path_provider: ^2.1.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

topics:
  - video-player